// Code generated by Slice Machine. DO NOT EDIT.

import HeroSection from './HeroSection/index.svelte';
import SquadA from './SquadA/index.svelte';
import SquadADetailPage from './SquadADetailPage/index.svelte';
import SquadB from './SquadB/index.svelte';
import SquadBDetailPage from './SquadBDetailPage/index.svelte';

export const components = {
	rich_text: HeroSection,
	squad_a: SquadA,
	squad_a_detail_page: SquadADetailPage,
	squad_b: SquadB,
	squad_b_detail_page: SquadBDetailPage
};
